name       : scdoc
version    : 1.9.7
release    : 2
source     :
    - https://git.sr.ht/~sircmpwn/scdoc/archive/1.9.7.tar.gz : 7e0ef0b2fdbe40d66461b1b2900aadd889a2d91eaecd2505e85fabf6db003779
license    : MIT
component  : system.utils
summary    : scdoc is a simple man page generator for POSIX systems written in C99.
description: |
    scdoc is a simple man page generator for POSIX systems written in C99.
patterns   :
    - /usr/lib/pkgconfig/scdoc.pc
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-version-number.patch
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
