name       : scdoc
version    : 1.11.0
release    : 5
source     :
    - https://git.sr.ht/~sircmpwn/scdoc/archive/1.11.0.tar.gz : 8ac3e7e08fdfab0d75a312b1abcb6eafbd9114a5deaafbaba0fe5ec7e880929d
license    : MIT
component  : system.utils
summary    : scdoc is a simple man page generator for POSIX systems written in C99.
description: |
    scdoc is a simple man page generator for POSIX systems written in C99.
patterns   :
    - /usr/lib/pkgconfig/scdoc.pc
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
