name       : scdoc
version    : 1.9.6
release    : 1
source     :
    - https://git.sr.ht/~sircmpwn/scdoc/archive/1.9.6.tar.gz : 89a5f2294b4b72ee1d20b8a478d16bee1f96b6202bfeedb6df76c27881ed5928
license    : MIT
component  : system.utils
summary    : scdoc is a simple man page generator for POSIX systems written in C99.
description: |
    scdoc is a simple man page generator for POSIX systems written in C99.
patterns   :
    - /usr/lib/pkgconfig/scdoc.pc
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
