name       : scdoc
version    : 1.11.1
release    : 7
source     :
    - https://git.sr.ht/~sircmpwn/scdoc/archive/1.11.1.tar.gz : e529fcb00508e7e4c5025a745591b805b754b3bd5c84c5192acaefabdfa8f700
license    : MIT
component  : system.utils
summary    : scdoc is a simple man page generator for POSIX systems written in C99.
description: |
    scdoc is a simple man page generator for POSIX systems written in C99.
patterns   :
    - /usr/lib/pkgconfig/scdoc.pc
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
