name       : scdoc
version    : 1.10.0
release    : 3
source     :
    - https://git.sr.ht/~sircmpwn/scdoc/archive/1.10.0.tar.gz : 3482e08b994cc4a528caf3d20dd70efda2d2ec86b30f66af75a1d192fee56852
license    : MIT
component  : system.utils
summary    : scdoc is a simple man page generator for POSIX systems written in C99.
description: |
    scdoc is a simple man page generator for POSIX systems written in C99.
patterns   :
    - /usr/lib/pkgconfig/scdoc.pc
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
