name       : scdoc
version    : 1.11.2
release    : 8
source     :
    - https://git.sr.ht/~sircmpwn/scdoc/archive/1.11.2.tar.gz : e9ff9981b5854301789a6778ee64ef1f6d1e5f4829a9dd3e58a9a63eacc2e6f0
license    : MIT
component  : system.utils
summary    : scdoc is a simple man page generator for POSIX systems written in C99.
description: |
    scdoc is a simple man page generator for POSIX systems written in C99.
patterns   :
    - /usr/share/pkgconfig/scdoc.pc
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
